version: "3.8"
services:
  mongo:
    image: geppettotest/mongo-local:april2020
    container_name: mongo-6365
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - hpticketapplicationone_6365-volume:/data/db
    ports:
      - "27018:27017"
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u root -p root --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  camunda:
    image: geppettodistribution/camunda-local:Jan2021
    container_name: camunda-6365
    ports:
      - "0000:8080"

  authproxy:
    build: ../../../application/services/default_services/authproxy
    image: authproxy-6365
    container_name: authproxy-6365
    ports:
      - "0000:8001"
    env_file: .env
    depends_on:
      - mongo
      - camunda

  securitymanager:
    build: ../../../application/services/default_services/securitymanager
    image: securitymanager-6365
    container_name: securitymanager-6365
    ports:
      - "8003:8003"
    env_file: .env
    depends_on:
      - mongo
      - camunda

  camundaservice:
    build: ../../../application/services/default_services/camunda
    image: camundaservice-6365
    container_name: camundasvc-6365
    ports:
      - "8002:8002"
    env_file: .env
    depends_on:
      - mongo
      - camunda
      - securitymanager

  apigateway:
    build: ../../../application/services/custom_services/apigateway
    image: apigateway-6365
    container_name: apigateway-6365
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - camunda
      - camundaservice
      - authproxy
      - securitymanager
      - ticket
      - servicetype
      - severity



  ticket: 
    build: ../../../application/services/custom_services/ticket
    image: ticket-6365
    container_name: ticket-6365
    ports: 
      - 8005:8005
    env_file: .env
    depends_on:
      - mongo

  servicetype: 
    build: ../../../application/services/custom_services/servicetype
    image: servicetype-6365
    container_name: servicetype-6365
    ports: 
      - 8006:8006
    env_file: .env
    depends_on:
      - mongo

  severity: 
    build: ../../../application/services/custom_services/severity
    image: severity-6365
    container_name: severity-6365
    ports: 
      - 8007:8007
    env_file: .env
    depends_on:
      - mongo


volumes:
  hpticketapplicationone_6365-volume:
    driver: local
